package com.lightfire.lib_emoji.emoji;

public class Yerler {
    public static final Emojiler[] DATA = new Emojiler[]{
            Emojiler.fromCodePoint(0x1f3e0),
            Emojiler.fromCodePoint(0x1f3e1),
            Emojiler.fromCodePoint(0x1f3eb),
            Emojiler.fromCodePoint(0x1f3e2),
            Emojiler.fromCodePoint(0x1f3e3),
            Emojiler.fromCodePoint(0x1f3e5),
            Emojiler.fromCodePoint(0x1f3e6),
            Emojiler.fromCodePoint(0x1f3ea),
            Emojiler.fromCodePoint(0x1f3e9),
            Emojiler.fromCodePoint(0x1f3e8),
            Emojiler.fromCodePoint(0x1f492),
            Emojiler.fromChar((char) 0x26ea),
            Emojiler.fromCodePoint(0x1f3ec),
            Emojiler.fromCodePoint(0x1f3e4),
            Emojiler.fromCodePoint(0x1f307),
            Emojiler.fromCodePoint(0x1f306),
            Emojiler.fromCodePoint(0x1f3ef),
            Emojiler.fromCodePoint(0x1f3f0),
            Emojiler.fromChar((char) 0x26fa),
            Emojiler.fromCodePoint(0x1f3ed),
            Emojiler.fromCodePoint(0x1f5fc),
            Emojiler.fromCodePoint(0x1f5fe),
            Emojiler.fromCodePoint(0x1f5fb),
            Emojiler.fromCodePoint(0x1f304),
            Emojiler.fromCodePoint(0x1f305),
            Emojiler.fromCodePoint(0x1f303),
            Emojiler.fromCodePoint(0x1f5fd),
            Emojiler.fromCodePoint(0x1f309),
            Emojiler.fromCodePoint(0x1f3a0),
            Emojiler.fromCodePoint(0x1f3a1),
            Emojiler.fromChar((char) 0x26f2),
            Emojiler.fromCodePoint(0x1f3a2),
            Emojiler.fromCodePoint(0x1f6a2),
            Emojiler.fromChar((char) 0x26f5),
            Emojiler.fromCodePoint(0x1f6a4),
            Emojiler.fromCodePoint(0x1f6a3),
            Emojiler.fromChar((char) 0x2693),
            Emojiler.fromCodePoint(0x1f680),
            Emojiler.fromChar((char) 0x2708),
            Emojiler.fromCodePoint(0x1f4ba),
            Emojiler.fromCodePoint(0x1f681),
            Emojiler.fromCodePoint(0x1f682),
            Emojiler.fromCodePoint(0x1f68a),
            Emojiler.fromCodePoint(0x1f689),
            Emojiler.fromCodePoint(0x1f69e),
            Emojiler.fromCodePoint(0x1f686),
            Emojiler.fromCodePoint(0x1f684),
            Emojiler.fromCodePoint(0x1f685),
            Emojiler.fromCodePoint(0x1f688),
            Emojiler.fromCodePoint(0x1f687),
            Emojiler.fromCodePoint(0x1f69d),
            Emojiler.fromCodePoint(0x1f68b),
            Emojiler.fromCodePoint(0x1f683),
            Emojiler.fromCodePoint(0x1f68e),
            Emojiler.fromCodePoint(0x1f68c),
            Emojiler.fromCodePoint(0x1f68d),
            Emojiler.fromCodePoint(0x1f699),
            Emojiler.fromCodePoint(0x1f698),
            Emojiler.fromCodePoint(0x1f697),
            Emojiler.fromCodePoint(0x1f695),
            Emojiler.fromCodePoint(0x1f696),
            Emojiler.fromCodePoint(0x1f69b),
            Emojiler.fromCodePoint(0x1f69a),
            Emojiler.fromCodePoint(0x1f6a8),
            Emojiler.fromCodePoint(0x1f693),
            Emojiler.fromCodePoint(0x1f694),
            Emojiler.fromCodePoint(0x1f692),
            Emojiler.fromCodePoint(0x1f691),
            Emojiler.fromCodePoint(0x1f690),
            Emojiler.fromCodePoint(0x1f6b2),
            Emojiler.fromCodePoint(0x1f6a1),
            Emojiler.fromCodePoint(0x1f69f),
            Emojiler.fromCodePoint(0x1f6a0),
            Emojiler.fromCodePoint(0x1f69c),
            Emojiler.fromCodePoint(0x1f488),
            Emojiler.fromCodePoint(0x1f68f),
            Emojiler.fromCodePoint(0x1f3ab),
            Emojiler.fromCodePoint(0x1f6a6),
            Emojiler.fromCodePoint(0x1f6a5),
            Emojiler.fromChar((char) 0x26a0),
            Emojiler.fromCodePoint(0x1f6a7),
            Emojiler.fromCodePoint(0x1f530),
            Emojiler.fromChar((char) 0x26fd),
            Emojiler.fromCodePoint(0x1f3ee),
            Emojiler.fromCodePoint(0x1f3b0),
            Emojiler.fromChar((char) 0x2668),
            Emojiler.fromCodePoint(0x1f5ff),
            Emojiler.fromCodePoint(0x1f3aa),
            Emojiler.fromCodePoint(0x1f3ad),
            Emojiler.fromCodePoint(0x1f4cd),
            Emojiler.fromCodePoint(0x1f6a9),
            Emojiler.fromChars("\ud83c\uddef\ud83c\uddf5"),
            Emojiler.fromChars("\ud83c\uddf0\ud83c\uddf7"),
            Emojiler.fromChars("\ud83c\udde9\ud83c\uddea"),
            Emojiler.fromChars("\ud83c\udde8\ud83c\uddf3"),
            Emojiler.fromChars("\ud83c\uddfa\ud83c\uddf8"),
            Emojiler.fromChars("\ud83c\uddeb\ud83c\uddf7"),
            Emojiler.fromChars("\ud83c\uddea\ud83c\uddf8"),
            Emojiler.fromChars("\ud83c\uddee\ud83c\uddf9"),
            Emojiler.fromChars("\ud83c\uddf7\ud83c\uddfa"),
            Emojiler.fromChars("\ud83c\uddec\ud83c\udde7"),
    };
}
